
import { Navbar } from "../components";
import Layout from "../components/Layout";
import LandingPage from "./landing";
import Categories from "./landing/Categories";
import Contact from "./landing/Contact";
import FAQ from "./landing/FAQ";
import SearchRooms from "./landing/SearchRooms";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const Main = () => {

  return (
    <Layout>
      <Navbar/>
      <div className="page">
        <main>
          <div className="">
            <LandingPage/>
            <Categories/>
            <SearchRooms/>
            <FAQ/>
            <Contact/>
          </div>
        </main>
      </div>
    </Layout>
  );
};

export default Main;
